# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

#Using a Self-hosted machine
#Windows: VahilaLocalPool
#Linux: Vahila-linux-jenkinsci-01-ah  
resources:
  pipelines:
    - pipeline: azure-pipeline
      source: test-setup
      trigger: true

trigger: none 

strategy:
  matrix:
#     linux:
#       imageName: 'Linux_QE'
#     mac:
#       imageName: 'Mac_QE'
    windows:
      imageName: 'win_devpool'

pool:
  name: Default
  demands:
    - agent.name -equals $(agentName)

trigger:
  - master

steps:
  - script: mw -using bci mvn test
  
