# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# trigger:
#  branches:
#     include:
#     - IntegTests

# jobs:
# - job: Test
#   timeoutInMinutes: 120
#   strategy:
#     matrix:
#       linux:
#         vmss: LinuxVMSS
# #       windows:
# #         vmss: WindowsVMSS
#   pool:
#     name: $(vmss)
#     vmImage: #
#   steps:
#     - script: git --version
#     - script: git clone https://insidelabs-git.mathworks.com/cit/utilities/network-license-manager-docker

pool:
   vmImage: 'ubuntu-latest'

steps:
 - script: wget https://www.mathworks.com/mpm/glnxa64/mpm && chmod +x mpm && ./mpm install --release=R2022a --destination=matlab --products MATLAB && ls matlab && export PATH=matlab/bin:$PATH && echo $PATH && pwd 
 - script: pwd
 - script: mkdir matlab/licenses && touch matlab/licenses/license.lic
 - script: cat matlab/licenses/license.lic
 - script: echo "$LINUX_R2022A" > matlab/licenses/license.lic && cat matlab/licenses/license.lic
 - script: export PATH=matlab/bin:$PATH && matlab -batch ver,pwd
