# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
 branches:
    include:
    - IntegTests

jobs:
- job: Test
  timeoutInMinutes: 120
  strategy:
    matrix:
      linux:
        vmss: LinuxVMSS
      windows:
        vmss: WindowsVMSS
  pool:
    name: $(vmss)
    vmImage: #
  steps:
    - script: mvn verify
