# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

#Using a Self-hosted machine
#Windows: VahilaLocalPool
#Linux: Vahila-linux-jenkinsci-01-ah  
# resources:
#   pipelines:
#     - pipeline: azure-pipeline
#       source: test-setup
#       trigger: true

# trigger: none 

pool:
  name: Default
  demands:
    - agent.name -equals $(imageName)

trigger:
 - master
  
  
jobs:
- job: Test
  timeoutInMinutes: 120
  strategy:
  matrix:
    linux:
      imageName: 'linux_vm_vahila'
    mac:
      imageName: 'vahila_mac_bgl'
    windows:
      imageName: 'vahila_win_bgl'

    steps:
    - script: mw -using bci mvn clean verify
  
