name: using mpm to install MATLAB
on: push
jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
#       - name: Set up JDK 14
#         uses: actions/setup-java@v1
#         with:
#           java-version: 14
#       - name: Get mpm
#         run: wget https://www.mathworks.com/mpm/glnxa64/mpm && chmod +x mpm 
#       - name: MATLAB install dir
#         run: mkdir matlab
#       - name: Install MATLAB
#         run: ./mpm install --release=R2021b --destination=matlab --products MATLAB 
      - name: Add matlab to path
        run: export PATH=$(pwd):$PATH && printenv PATH && printenv JAVA_HOME
#       - name: Set up MATLAB
#         uses: matlab-actions/setup-matlab@v1
#       - name: MATLAB-2021b
#         uses: matlab-actions/setup-matlab@v1
#         with:
#           release: R2021b
#       - name: MATLAB-2022a
#         uses: matlab-actions/setup-matlab@v1
#         with:
#           release: R2022a

      - name: Check contents of matlab folder
        run: cd matlab && ls
      - name: Get license
        run: cd matlab && mkdir licenses  && cd licenses && pwd &&  printenv LINUX_LIC > "license.lic" && ls
        env:
          LINUX_LIC:  ${{ secrets.LINUX_R2022A}}
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: matlab/licenses/license.lic
      - name: Run matlab command
        run: export PATH=$(pwd)/matlab/bin:$PATH && printenv PATH && matlab -batch matlabroot, ver, parpool
          
#       - name: Run script
#         uses: matlab-actions/run-command@v1
#         with:
#           command: matlabroot, ver, parpool
#       - name: Build project with Maven
#         run: mvn clean test-compile failsafe:integration-test
 
#     name: Install MATLAB
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get mpm
#         run: wget https://www.mathworks.com/mpm/glnxa64/mpm && chmod +x mpm 
# #       - name: Install MATLAB
# #         run: ./mpm install --release=R2022a --destination=matlab --products MATLAB
#       - name: Create license Directory and file
#         run: mkdir matlab && mkdir matlab/licenses && touch matlab/licenses/license.lic
#       - name: base64 encoding
#         run: echo "$LINUX_R2022A" > matlab/licenses/license_enc.lic &&cat matlab/licenses/license_enc.lic | base64 -d > matlab/licenses/license.lic
#       - name: Get license
#         run: printenv LINUX_LIC > "matlab/licenses/license.lic" && cat matlab/licenses/license.lic
#         env:
#           LINUX_LIC: ${{ secrets.LINUX_R2022A }}
#       - name: test substring
#         run: grep -q "ab\ncd" matlab/licenses/license.lic && echo "yes" || echo "no"
#       - name: Run MATLAB
#         run: export PATH=matlab/bin:$PATH && matlab -batch ver,pwd
      
