name: using mpm to install MATLAB
on: push
jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: matlabroot
      - name: Build project with Maven
        run: mvn failsafe:integration-test
 
#     name: Install MATLAB
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get mpm
#         run: wget https://www.mathworks.com/mpm/glnxa64/mpm && chmod +x mpm 
# #       - name: Install MATLAB
# #         run: ./mpm install --release=R2022a --destination=matlab --products MATLAB
#       - name: Create license Directory and file
#         run: mkdir matlab && mkdir matlab/licenses && touch matlab/licenses/license.lic
#       - name: base64 encoding
#         run: echo "$LINUX_R2022A" > matlab/licenses/license_enc.lic &&cat matlab/licenses/license_enc.lic | base64 -d > matlab/licenses/license.lic
#       - name: Get license
#         run: printenv LINUX_LIC > "matlab/licenses/license.lic" && cat matlab/licenses/license.lic
#         env:
#           LINUX_LIC: ${{ secrets.LINUX_R2022A }}
#       - name: test substring
#         run: grep -q "ab\ncd" matlab/licenses/license.lic && echo "yes" || echo "no"
#       - name: Run MATLAB
#         run: export PATH=matlab/bin:$PATH && matlab -batch ver,pwd
      
