name: using mpm to install MATLAB
on: push
jobs:
  my-job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Run System tests
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup MATLAB
        id: setup-matlab
        uses: matlab-actions/setup-matlab@v2

      - name: Running tests
        run: mvn test-compile failsafe:integration-test
        env:
          MATLAB_ROOT: ${{ steps.setup-matlab.outputs.matlabroot }}
          MLM_LICENSE_TOKEN:  ${{ secrets.MLM_LICENSE_TOKEN}}